# Generated by Django 5.2.8 on 2025-12-02 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0003_systemsetting_notificationsetting_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='location',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
