# Generated by Django 5.2.8 on 2025-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0004_remove_material_location_remove_material_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='added_by',
            field=models.TextField(blank=True),
        ),
    ]
