# Generated by Django 5.2.8 on 2025-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0005_alter_material_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='material',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
