# Generated by Django 5.2.8 on 2025-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0006_remove_material_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
