# Generated by Django 5.2.8 on 2025-12-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0007_alter_material_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Dish', 'Dish')], max_length=20),
        ),
    ]
