# Generated by Django 5.2.8 on 2025-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0008_alter_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock'), ('Reserved', 'Reserved'), ('Deprecated', 'Deprecated')], default='Normal', max_length=20),
        ),
    ]
