# Generated by Django 6.0 on 2026-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0010_usedmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
    ]
