# Generated by Django 6.0 on 2026-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0011_materialrequest_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='user_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='issue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='admin_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
