# Generated by Django 6.0.1 on 2026-01-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0012_materialrequest_user_note_usedmaterial_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Serial_MAC',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='added_by',
            field=models.CharField(max_length=100),
        ),
    ]
