# Generated by Django 6.0.1 on 2026-01-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0013_material_serial_mac_alter_material_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='Serial_MAC',
        ),
    ]
