# Generated by Django 6.0.1 on 2026-01-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0014_remove_material_serial_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='client_address',
            field=models.TextField(blank=True, verbose_name='Client Address'),
        ),
    ]
