# Generated by Django 6.0 on 2026-01-30 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0015_usedmaterial_client_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedmaterial',
            options={'ordering': ['-added_at'], 'verbose_name': 'Used Material', 'verbose_name_plural': 'Used Materials'},
        ),
        migrations.RemoveField(
            model_name='usedmaterial',
            name='address',
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Client Phone'),
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin Notes'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='issue',
            field=models.TextField(blank=True, verbose_name='Technical Issue / Notes'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_instances', to='isp_inventory.material'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['technician', '-added_at'], name='isp_invento_technic_1a7ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['material', '-added_at'], name='isp_invento_materia_7380a5_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['status'], name='isp_invento_status_ec4862_idx'),
        ),
    ]
