# Generated by Django 6.0.1 on 2026-02-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0018_remove_usedmaterial_material_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Storekeeper', 'Storekeeper'), ('Technician', 'Technician'), ('NOC', 'NOC')], default='Technician', max_length=20),
        ),
    ]
