# Generated by Django 6.0.1 on 2026-02-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0021_alter_material_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
