# Generated by Django 6.0.1 on 2026-02-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0022_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='backupandrestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(upload_to='backups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
