# Generated by Django 6.0.1 on 2026-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0023_backupandrestore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='technician',
            new_name='Branch',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Storekeeper', 'Storekeeper'), ('Branch', 'Branch'), ('NOC', 'NOC')], default='Branch', max_length=20),
        ),
    ]
