# Generated by Django 6.0.1 on 2026-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0024_rename_technician_task_branch_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='request_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Advance', 'Advance')], default='Regular', max_length=20),
        ),
    ]
