# Generated by Django 6.0.1 on 2026-02-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0026_announcement_message'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='isp_invento_is_acti_c4cbf7_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='isp_invento_priorit_711b3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='isp_invento_recipie_ea171f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='isp_invento_sender__f10e20_idx',
        ),
        migrations.RenameField(
            model_name='materialrequest',
            old_name='user_note',
            new_name='send_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
