# Generated by Django 6.0.1 on 2026-02-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0027_remove_announcement_isp_invento_is_acti_c4cbf7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Dish', 'Dish'), ('Fiber', 'Fiber'), ('Common item', 'Common item'), ('Work shop', 'Work shop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='Normal', max_length=20),
        ),
    ]
