# Generated by Django 6.0 on 2026-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0028_remove_material_added_by_alter_material_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='received_by',
            field=models.TextField(blank=True),
        ),
    ]
