# Generated by Django 6.0 on 2026-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0029_materialrequest_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_by_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Storekeeper', 'Storekeeper'), ('Branch', 'Branch'), ('NOC', 'NOC')], default='Admin', max_length=20),
        ),
    ]
