# Generated by Django 6.0.1 on 2026-02-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0030_material_created_by_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='created_by_role',
        ),
        migrations.CreateModel(
            name='MaterialMonthlyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month for which count is tracked')),
                ('count', models.IntegerField(default=0, help_text='Monthly count that resets at month end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_counts', to='isp_inventory.material')),
            ],
            options={
                'verbose_name': 'Material Monthly Count',
                'verbose_name_plural': 'Material Monthly Counts',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['material', '-month'], name='isp_invento_materia_1b2ada_idx'), models.Index(fields=['month'], name='isp_invento_month_2744f5_idx')],
                'unique_together': {('material', 'month')},
            },
        ),
    ]
