# Generated by Django 6.0.1 on 2026-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0034_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Remaining_stock',
            field=models.IntegerField(default=0),
        ),
    ]
