# Generated by Django 6.0 on 2026-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0040_userprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Material Type (e.g. Meter, Piece)'),
        ),
    ]
