# Generated by Django 6.0 on 2026-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0041_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='Type',
            field=models.CharField(choices=[('Meter', 'Meter'), ('Piece', 'Piece')], default='Piece', max_length=10),
        ),
    ]
