# Generated by Django 6.0 on 2026-04-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0043_alter_material_name_alter_usedmaterial_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.FileField(upload_to='backups/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('partial', 'Partial Backup')], default='full', max_length=20)),
                ('backup_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('description', models.TextField(blank=True, help_text='Optional backup description', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted (Recoverable)'), ('purged', 'Permanently Purged')], default='active', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('data_records_count', models.IntegerField(default=0, help_text='Number of data records in backup')),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum for integrity verification', max_length=64, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this backup', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_deleted', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup & Restore',
                'verbose_name_plural': 'Backups & Restores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='backupandrestore',
        ),
    ]
