# Generated by Django 6.0 on 2026-04-04 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0044_backuprestore_delete_backupandrestore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsetting',
            options={'verbose_name': 'Notification Setting', 'verbose_name_plural': 'Notification Settings'},
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='backup_alert',
            field=models.BooleanField(default=True, help_text='Notify on backup operations'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='in_app_notifications',
            field=models.BooleanField(default=True, help_text='Show in-app notifications'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='material_destroyed_alert',
            field=models.BooleanField(default=True, help_text='Notify when material is destroyed'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='message_alert',
            field=models.BooleanField(default=True, help_text='Notify on new messages'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='out_of_stock_alert',
            field=models.BooleanField(default=True, help_text='Alert when item is out of stock'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='request_approved_alert',
            field=models.BooleanField(default=True, help_text='Notify when request is approved'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='request_rejected_alert',
            field=models.BooleanField(default=True, help_text='Notify when request is rejected'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='system_alert',
            field=models.BooleanField(default=False, help_text='System-level alerts'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='task_completed_alert',
            field=models.BooleanField(default=True, help_text='Notify when task is completed'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='low_stock_alert',
            field=models.BooleanField(default=True, help_text='Alert when stock is low'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='new_request_alert',
            field=models.BooleanField(default=True, help_text='Notify on new material requests'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='task_assignment_alert',
            field=models.BooleanField(default=True, help_text='Notify when task is assigned'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug - Detailed information'), ('INFO', 'Info - General information'), ('WARNING', 'Warning - Warning messages'), ('ERROR', 'Error - Error messages'), ('CRITICAL', 'Critical - Critical errors')], default='INFO', max_length=20)),
                ('enable_file_logging', models.BooleanField(default=True, help_text='Save logs to file')),
                ('enable_database_logging', models.BooleanField(default=True, help_text='Save activity logs to database')),
                ('log_user_activities', models.BooleanField(default=True, help_text='Track user login/logout')),
                ('log_file_path', models.CharField(default='logs/app.log', help_text='Path where logs are saved', max_length=500)),
                ('max_log_file_size', models.IntegerField(default=10485760, help_text='Max log file size in bytes (10MB default)')),
                ('backup_count', models.IntegerField(default=5, help_text='Number of backup log files to keep')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Settings',
                'verbose_name_plural': 'Log Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Action'), ('update', 'Update Action'), ('delete', 'Delete Action'), ('approve', 'Approval Action'), ('reject', 'Rejection Action'), ('download', 'Download Action'), ('restore', 'Restore Action'), ('other', 'Other Action')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Action description')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Device info')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='isp_invento_user_id_e9ed0d_idx'), models.Index(fields=['activity_type', '-timestamp'], name='isp_invento_activit_d16e6d_idx')],
            },
        ),
    ]
