# Generated by Django 6.0 on 2026-04-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0045_alter_notificationsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the request was archived', null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Auto-archived for previous months'),
        ),
    ]
