# Generated by Django 6.0 on 2026-04-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0046_add_archive_fields_to_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the used material was archived', null=True),
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Auto-archived for previous months'),
        ),
    ]
