# Generated by Django 6.0 on 2026-04-23 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0047_add_archive_fields_to_usedmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='material_request',
            field=models.ForeignKey(blank=True, help_text='Associated MaterialRequest from branch user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_materials', to='isp_inventory.materialrequest'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['material_request', 'technician'], name='isp_invento_materia_9506b1_idx'),
        ),
    ]
