# Generated by Django 6.0.4 on 2026-04-29 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0049_alter_userprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_serial', models.CharField(help_text='Unique Mac/Serial number', max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity for this mac/serial')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Retired', 'Retired')], default='Active', help_text='Current status of this Mac/Serial entry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='NOC user who added this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_mac_serials', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Branch user this is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mac_serials', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_serials', to='isp_inventory.material')),
            ],
            options={
                'verbose_name': 'Mac/Serial Number',
                'verbose_name_plural': 'Mac/Serial Numbers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material', '-created_at'], name='isp_invento_materia_033236_idx'), models.Index(fields=['assigned_to', '-created_at'], name='isp_invento_assigne_279889_idx'), models.Index(fields=['status'], name='isp_invento_status_1f6663_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialMacSerialImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('total_quantity', models.IntegerField(default=1, help_text='Total quantity for this import')),
                ('mac_serials_count', models.IntegerField(default=0, help_text='Number of mac/serial entries')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Who approved this import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mac_serial_imports', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='Branch user receiving the materials', on_delete=django.db.models.deletion.CASCADE, related_name='mac_serial_imports', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_serial_imports', to='isp_inventory.material')),
                ('noc_user', models.ForeignKey(blank=True, help_text='NOC user who created this import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mac_serial_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Mac/Serial Import',
                'verbose_name_plural': 'Material Mac/Serial Imports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', '-created_at'], name='isp_invento_assigne_e0162c_idx'), models.Index(fields=['status', '-created_at'], name='isp_invento_status_985e41_idx')],
            },
        ),
    ]
