# Generated by Django 6.0 on 2026-04-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0050_macserialnumber_materialmacserialimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='mac_serial',
            field=models.ForeignKey(blank=True, help_text='Specific Mac/Serial number used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_records', to='isp_inventory.macserialnumber'),
        ),
        migrations.AlterField(
            model_name='macserialnumber',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Transferred', 'Transferred'), ('Retired', 'Retired')], default='Active', help_text='Current status of this Mac/Serial entry', max_length=20),
        ),
    ]
