# Generated by Django 6.0 on 2026-05-03 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0051_usedmaterial_mac_serial_alter_macserialnumber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='pass_on',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='pass_on_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Dispatched', 'Dispatched'), ('Received', 'Received'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
