# Generated by Django 6.0.4 on 2026-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0052_materialrequest_pass_on_materialrequest_pass_on_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='per_rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
