# Generated by Django 6.0.4 on 2026-05-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0053_materialrequest_per_rate_materialrequest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='per_rate',
        ),
    ]
