# Generated by Django 6.0 on 2026-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0054_remove_materialrequest_per_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
