# Generated by Django 6.0 on 2026-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0055_material_rate_material_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='deducted_from_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='deducted_from_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
