# Generated by Django 6.0.4 on 2026-05-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0056_materialrequest_deducted_from_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
