# Generated by Django 6.0 on 2026-05-17 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0057_material_deleted_at_material_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('damage_reason', models.TextField(blank=True, verbose_name='Reason for Damage')),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Moderate', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('branch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_materials', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_damages', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_instances', to='isp_inventory.material')),
            ],
            options={
                'verbose_name': 'Damage Material',
                'verbose_name_plural': 'Damage Materials',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['branch_user', '-added_at'], name='isp_invento_branch__656c67_idx'), models.Index(fields=['material', '-added_at'], name='isp_invento_materia_c64126_idx'), models.Index(fields=['status'], name='isp_invento_status_1594c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefundableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('issue', models.TextField(blank=True, verbose_name='Reason for Refund')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refundable_materials', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refundable_instances', to='isp_inventory.material')),
            ],
            options={
                'verbose_name': 'Refundable Material',
                'verbose_name_plural': 'Refundable Materials',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['branch_user', '-added_at'], name='isp_invento_branch__9b77a2_idx'), models.Index(fields=['material', '-added_at'], name='isp_invento_materia_c64e89_idx'), models.Index(fields=['status'], name='isp_invento_status_725295_idx')],
            },
        ),
    ]
