# Generated by Django 6.0 on 2026-05-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0058_damagematerial_refundablematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='is_hidden_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='is_hidden_by_noc',
            field=models.BooleanField(default=False),
        ),
    ]
