# Generated by Django 6.0.5 on 2026-05-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0059_materialrequest_is_hidden_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagematerial',
            name='severity',
        ),
        migrations.AddField(
            model_name='damagematerial',
            name='mac_serial',
            field=models.ForeignKey(blank=True, help_text='Specific Mac/Serial number damaged', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_records', to='isp_inventory.macserialnumber'),
        ),
    ]
