# Generated by Django 6.0.5 on 2026-06-05 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0060_remove_damagematerial_severity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Internal Message', 'verbose_name_plural': 'Internal Messages'},
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Real-time analysis results (sentiment, keywords, etc.)'),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='analyzed_at_bd',
            field=models.DateTimeField(blank=True, help_text='When message was analyzed in BD timezone (UTC+6)', null=True),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='created_at_bd',
            field=models.DateTimeField(blank=True, help_text='Creation timestamp in BD timezone (UTC+6)', null=True),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='is_analyzed',
            field=models.BooleanField(default=False, help_text='Flag for real-time analysis completion'),
        ),
        migrations.AlterField(
            model_name='internalmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in UTC'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['sender', '-created_at'], name='isp_invento_sender__db049b_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['receiver', '-created_at'], name='isp_invento_receive_865695_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='isp_invento_is_read_efb4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmessage',
            index=models.Index(fields=['is_analyzed', '-created_at'], name='isp_invento_is_anal_b5d124_idx'),
        ),
    ]
