# Generated by Django 6.0.5 on 2026-06-06 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0061_alter_internalmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundableMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_quantity', models.IntegerField(default=1)),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Client Name')),
                ('client_address', models.TextField(blank=True, verbose_name='Client Address')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Client Phone')),
                ('issue', models.TextField(blank=True, verbose_name='Technical Issue / Notes')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Refundable Material Usage',
                'verbose_name_plural': 'Refundable Material Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='refundablematerial',
            name='isp_invento_materia_c64e89_idx',
        ),
        migrations.RemoveIndex(
            model_name='refundablematerial',
            name='isp_invento_status_725295_idx',
        ),
        migrations.AddField(
            model_name='refundablematerial',
            name='material_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='refundablematerial',
            index=models.Index(fields=['quantity'], name='isp_invento_quantit_45cbfb_idx'),
        ),
        migrations.AddField(
            model_name='refundablematerialusage',
            name='refundable_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='isp_inventory.refundablematerial'),
        ),
        migrations.AddField(
            model_name='refundablematerialusage',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_refundable_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='refundablematerial',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='refundablematerial',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='refundablematerial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='refundablematerial',
            name='status',
        ),
        migrations.AddIndex(
            model_name='refundablematerialusage',
            index=models.Index(fields=['used_by', '-used_at'], name='isp_invento_used_by_c491fa_idx'),
        ),
        migrations.AddIndex(
            model_name='refundablematerialusage',
            index=models.Index(fields=['refundable_material', '-used_at'], name='isp_invento_refunda_91f9d1_idx'),
        ),
    ]
