# Generated by Django 6.0.5 on 2026-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0062_refundablematerialusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundablematerial',
            name='mac_serial',
            field=models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Mac/Serial'),
        ),
    ]
