# Generated by Django 6.0.6 on 2026-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0063_refundablematerial_mac_serial'),
    ]

    def _make_mac_serials_unique(apps, schema_editor):
        RefundableMaterial = apps.get_model('isp_inventory', 'RefundableMaterial')
        seen = set()
        for obj in RefundableMaterial.objects.all().order_by('pk'):
            mac = obj.mac_serial or 'N/A'
            if mac in seen:
                obj.mac_serial = f"{mac}-{obj.pk}"
                obj.save(update_fields=['mac_serial'])
            else:
                seen.add(mac)

    operations = [
        migrations.RunPython(
            _make_mac_serials_unique,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='is_pop_entry',
            field=models.BooleanField(default=False, help_text='True if this entry was submitted via the POP/Server area usage modal'),
        ),
        migrations.AlterField(
            model_name='refundablematerial',
            name='mac_serial',
            field=models.CharField(blank=True, default='N/A', max_length=200, unique=True, verbose_name='Mac/Serial'),
        ),
    ]
