# Generated by migration assistant
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0064_usedmaterial_is_pop_entry_and_more'),
    ]

    def set_na_to_null(apps, schema_editor):
        RefundableMaterial = apps.get_model('isp_inventory', 'RefundableMaterial')
        RefundableMaterial.objects.filter(mac_serial='N/A').update(mac_serial=None)

    operations = [
        migrations.AlterField(
            model_name='refundablematerial',
            name='mac_serial',
            field=models.CharField(max_length=200, null=True, blank=True, unique=True, verbose_name='Mac/Serial'),
        ),
        migrations.RunPython(set_na_to_null, migrations.RunPython.noop),
    ]
