# Generated by Django 6.0.5 on 2026-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0065_refundablematerial_mac_serial_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='macserialnumber',
            name='is_ever_accepted',
            field=models.BooleanField(default=False, help_text='True once this serial has been accepted at least once; prevents re-use after rejection'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
