# Generated by Django 6.0.5 on 2026-07-25 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0066_mac_serial_is_ever_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('item_type', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('serialized_data', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_restored', models.BooleanField(default=False)),
                ('is_permanently_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trash Item',
                'verbose_name_plural': 'Trash Items',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['user', '-deleted_at'], name='isp_invento_user_id_da7a54_idx'), models.Index(fields=['expires_at'], name='isp_invento_expires_c75db8_idx'), models.Index(fields=['is_restored', 'is_permanently_deleted'], name='isp_invento_is_rest_bbf1b5_idx')],
            },
        ),
    ]
