# Generated by Django 5.2.16 on 2026-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0067_trashitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='dispatched_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dispatched To'),
        ),
    ]
