# Generated by Django 5.2.16 on 2026-08-03 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0068_usedmaterial_dispatched_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Material Request', 'verbose_name_plural': 'Material Requests'},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='isp_invento_name_a0df8b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category'], name='isp_invento_categor_8e4934_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status'], name='isp_invento_status_4f0c73_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_deleted'], name='isp_invento_is_dele_2bae25_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['created_by'], name='isp_invento_created_15294d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['status', '-requested_at'], name='isp_invento_status_ef649c_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['requester', '-requested_at'], name='isp_invento_request_3b2dae_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['material', '-requested_at'], name='isp_invento_materia_40f61d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['is_archived'], name='isp_invento_is_arch_d61158_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['is_hidden_by_admin'], name='isp_invento_is_hidd_cadace_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['is_hidden_by_noc'], name='isp_invento_is_hidd_defab1_idx'),
        ),
    ]
