# Generated by Django 5.0.7 on 2026-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0069_alter_material_options_alter_materialrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedmaterial',
            name='dispatched_to',
            field=models.CharField(max_length=200, verbose_name='Dispatched To'),
        ),
    ]
