# Generated by Django 5.0.7 on 2026-08-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0070_dispatched_to_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundablematerialusage',
            name='dispatched_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dispatched To'),
        ),
    ]
