# Generated by Django 5.0.7 on 2026-08-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0071_refundablematerialusage_dispatched_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
