# Generated by Django 6.0.5 on 2026-08-25 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0072_alter_material_rate_alter_material_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='isp_invento_timesta_19dafd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='isp_invento_timesta_d8b6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='damagematerial',
            index=models.Index(fields=['-added_at'], name='isp_invento_added_a_677564_idx'),
        ),
        migrations.AddIndex(
            model_name='damagematerial',
            index=models.Index(fields=['branch_user', 'material'], name='isp_invento_branch__2af41b_idx'),
        ),
        migrations.AddIndex(
            model_name='macserialnumber',
            index=models.Index(fields=['-created_at'], name='isp_invento_created_cce145_idx'),
        ),
        migrations.AddIndex(
            model_name='macserialnumber',
            index=models.Index(fields=['mac_serial'], name='isp_invento_mac_ser_d2ebf1_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-added_at'], name='isp_invento_added_a_83c120_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status', 'quantity'], name='isp_invento_status_0e38b6_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['-requested_at'], name='isp_invento_request_38d276_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['is_archived', '-requested_at'], name='isp_invento_is_arch_de59c3_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['requester', 'status', 'is_archived'], name='isp_invento_request_7050b8_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['requester', 'material', 'status'], name='isp_invento_request_6980bc_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['-added_at'], name='isp_invento_added_a_8527c2_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['is_archived', '-added_at'], name='isp_invento_is_arch_a7bf4a_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['technician', 'is_archived', '-added_at'], name='isp_invento_technic_0b4d80_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['technician', 'material', 'is_archived'], name='isp_invento_technic_5275e6_idx'),
        ),
    ]
