# Generated by Django 6.0.5 on 2026-09-04 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_inventory', '0073_activitylog_isp_invento_timesta_19dafd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
